// Generated by gencpp from file pc_side_programs/Motor.msg
// DO NOT EDIT!


#ifndef PC_SIDE_PROGRAMS_MESSAGE_MOTOR_H
#define PC_SIDE_PROGRAMS_MESSAGE_MOTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pc_side_programs
{
template <class ContainerAllocator>
struct Motor_
{
  typedef Motor_<ContainerAllocator> Type;

  Motor_()
    : motor_speed()  {
      motor_speed.assign(0);
  }
  Motor_(const ContainerAllocator& _alloc)
    : motor_speed()  {
  (void)_alloc;
      motor_speed.assign(0);
  }



   typedef boost::array<int32_t, 6>  _motor_speed_type;
  _motor_speed_type motor_speed;





  typedef boost::shared_ptr< ::pc_side_programs::Motor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pc_side_programs::Motor_<ContainerAllocator> const> ConstPtr;

}; // struct Motor_

typedef ::pc_side_programs::Motor_<std::allocator<void> > Motor;

typedef boost::shared_ptr< ::pc_side_programs::Motor > MotorPtr;
typedef boost::shared_ptr< ::pc_side_programs::Motor const> MotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pc_side_programs::Motor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pc_side_programs::Motor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pc_side_programs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'pc_side_programs': ['/home/murakami/catkin_ws/src/pc_side_programs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pc_side_programs::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pc_side_programs::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pc_side_programs::Motor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pc_side_programs::Motor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pc_side_programs::Motor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pc_side_programs::Motor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pc_side_programs::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2c8fc50808318a33c399242582c9409";
  }

  static const char* value(const ::pc_side_programs::Motor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2c8fc50808318a3ULL;
  static const uint64_t static_value2 = 0x3c399242582c9409ULL;
};

template<class ContainerAllocator>
struct DataType< ::pc_side_programs::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pc_side_programs/Motor";
  }

  static const char* value(const ::pc_side_programs::Motor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pc_side_programs::Motor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[6] motor_speed\n\
";
  }

  static const char* value(const ::pc_side_programs::Motor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pc_side_programs::Motor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Motor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pc_side_programs::Motor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pc_side_programs::Motor_<ContainerAllocator>& v)
  {
    s << indent << "motor_speed[]" << std::endl;
    for (size_t i = 0; i < v.motor_speed.size(); ++i)
    {
      s << indent << "  motor_speed[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.motor_speed[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PC_SIDE_PROGRAMS_MESSAGE_MOTOR_H
